### ISSUE TITLE
RequestCloudflare.get not a function

### ISSUE THREAD

**Issue by AlifGans** [stealify/request-cloudflare#8]
my code like this

var requestCloudflare = require('request-cloudflare');
 requestCloudflare.get('http://website.com/', function(error, response, body) {
  if (error) {
    console.log('Error occurred');
  } else {
    console.log(body, response);
  }
});

**Comment by noahbucks** [comment]
requestCloudflare.requestCloudflare.get() worked for me

**Comment by frank-dspeed** [comment]
@noahbucks maybe your using a transpiled version i did not update this long time
